spring:
  application:
    name: nst
    jwt:
      secret: "nstAdminUserEncryptionKeyLocal9f8e7d6c5b4a3f2e"
  datasource:
    url: jdbc:mysql://localhost:3306/nst_db
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8090
  servlet:
    context-path: /api/v1

logging:
  level:
    org:
      springframework:
        security : DEBUG